# .coderabbit.yaml
reviews:
  enabled: true
  # Enable reviews on all branches (or specify specific branches)
  branches:
    include: ["**"]  # All branches
    # OR specify branches:
    # include: ["feature/*", "bugfix/*"]
  # Optional: Disable the status message (if desired)
  review_status: false